// Language packs: English words explained in one language. The metadata lives
// here; the data (packs/<id>/dict.json, levels.json) is generated by
// tools/build_packs.py. Plain script, used by background.js, extension pages and tests.
const LexiBridgePacks = (() => {
  // Each level marks the words of harder lists than the ones it assumes known.
  const PACKS = [
    {id: 'en-zh-Hans', defLang: 'zh-Hans', label: '简体中文', defaultLevel: 'cet4', levels: [
      {id: 'basic', name: '入门', desc: '掌握中考词汇 · 标出高考、四级词汇'},
      {id: 'cet4', name: '大学四级', desc: '掌握中考、高考、四级词汇 · 标出六级词汇'},
      {id: 'ky', name: '四级 · 备考研', desc: '掌握中考、高考、四级词汇 · 标出六级、考研词汇'},
      {id: 'cet6', name: '大学六级', desc: '掌握四六级、考研词汇 · 标出托福、雅思词汇'},
      {id: 'gre', name: 'GRE', desc: '掌握托福、雅思词汇 · 标出 GRE 词汇'},
    ]},
  ];

  // Missing or unknown ids (storage written before packs existed) mean the first pack.
  function getPack(id) {
    return PACKS.find(p => p.id === id) ?? PACKS[0];
  }

  // The pack for a learner whose browser languages are `languages` (most preferred
  // first): Traditional Chinese for Taiwan, Hong Kong and Macau, else Simplified.
  // Only packs that exist are picked.
  function pickPack(languages) {
    for(const language of languages) {
      const tag = String(language).toLowerCase().replace('_', '-');
      if(!/^zh\b/.test(tag)) continue;
      return getPack(/^zh-(tw|hk|mo|hant)\b/.test(tag) ? 'en-zh-Hant' : 'en-zh-Hans');
    }
    return PACKS[0];
  }

  function getLevel(packId, levelId) {
    return getPack(packId).levels.find(l => l.id === levelId);
  }

  // {dict: Map(word -> definition), levels: {levelId: [word, ...]}}.
  // Extension pages and the service worker only.
  async function loadPack(pack) {
    const get = async(name) => (await fetch(chrome.runtime.getURL(`packs/${pack.id}/${name}`))).json();
    const [dict, levels] = await Promise.all([get('dict.json'), get('levels.json')]);
    return {dict: new Map(Object.entries(dict)), levels};
  }

  // Starting word list of a level: [["word", "definition"], ...]
  function levelWords(data, levelId) {
    return (data.levels[levelId] ?? []).map(word => [word, data.dict.get(word)]);
  }

  return {PACKS, getPack, pickPack, getLevel, loadPack, levelWords};
})();

if (typeof module !== 'undefined') module.exports = LexiBridgePacks;
