// Language packs: English words explained in one language. The metadata lives
// here; the data (packs/<id>/dict.json, levels.json) is generated by
// tools/build_packs.py. Plain script, used by background.js, extension pages and tests.
const LexiBridgePacks = (() => {
  const LB = typeof LexiBridge !== 'undefined' ? LexiBridge : require('./lexicon.js');

  // Each level marks every word of the harder lists, not just the next one.
  // band names the words a level marks and the next one knows; the word card shows it.
  // credit names the data sources, as their licenses ask; it shows on the level page.
  const PACKS = [
    {id: 'en-zh-Hans', defLang: 'zh-Hans', label: '简体中文', defaultLevel: 'cet4',
     credit: '词典与分级：ECDICT（MIT 许可证）', levels: [
      {id: 'basic', name: '入门', band: '高考 · 四级', desc: '掌握中考词汇 · 标出高考及更难的词'},
      {id: 'cet4', name: '大学四级', band: '六级 · 考研', desc: '掌握中考、高考、四级词汇 · 标出六级、考研及更难的词'},
      {id: 'cet6', name: '大学六级', band: '托福 · 雅思', desc: '掌握四六级、考研词汇 · 标出托福、雅思、GRE 词汇'},
      {id: 'gre', name: 'GRE', band: 'GRE', desc: '掌握托福、雅思词汇 · 标出 GRE 词汇'},
    ]},
    {id: 'en-zh-Hant', defLang: 'zh-Hant', label: '繁體中文', defaultLevel: 'b1',
     credit: '詞典：ECDICT（MIT 授權），以 OpenCC 轉為繁體。分級：CEFR-J Wordlist Version 1.6，東京外國語大學投野由紀夫研究室。',
     levels: [
      {id: 'a2', name: '國中', band: 'CEFR B1', desc: '掌握 CEFR A1–A2（≈ 全民英檢初級）・標出更難的單字'},
      {id: 'b1', name: '高中・學測', band: 'CEFR B2', desc: '掌握 CEFR B1（≈ 全民英檢中級）・標出更難的單字'},
      {id: 'b2', name: '全民英檢中高級', band: '托福・雅思', desc: '掌握 CEFR B2・標出托福、雅思、GRE 單字'},
      {id: 'gre', name: 'GRE', band: 'GRE', desc: '掌握托福、雅思單字・標出 GRE 單字'},
    ]},
  ];

  // Missing or unknown ids (storage written before packs existed) mean the first pack.
  function getPack(id) {
    return PACKS.find(p => p.id === id) ?? PACKS[0];
  }

  // The pack for a learner whose browser languages are `languages` (most preferred
  // first): Traditional Chinese for Taiwan, Hong Kong and Macau, else Simplified.
  // Only packs that exist are picked.
  function pickPack(languages) {
    for(const language of languages) {
      const tag = String(language).toLowerCase().replace('_', '-');
      if(!/^zh\b/.test(tag)) continue;
      return getPack(/^zh-(tw|hk|mo|hant)\b/.test(tag) ? 'en-zh-Hant' : 'en-zh-Hans');
    }
    return PACKS[0];
  }

  function getLevel(packId, levelId) {
    return getPack(packId).levels.find(l => l.id === levelId);
  }

  // {levelId: [word, ...]}. Extension pages and the service worker only.
  async function loadLevels(pack) {
    return (await fetch(chrome.runtime.getURL(`packs/${pack.id}/levels.json`))).json();
  }

  // {dict: Map(word -> definition), levels: {levelId: [word, ...]}}.
  async function loadPack(pack) {
    const [dict, levels] = await Promise.all([
      fetch(chrome.runtime.getURL(`packs/${pack.id}/dict.json`)).then(res => res.json()), loadLevels(pack)]);
    return {dict: new Map(Object.entries(dict)), levels};
  }

  // Starting word list of a level: [["word", "definition"], ...]
  function levelWords(data, levelId) {
    return (data.levels[levelId] ?? []).map(word => [word, data.dict.get(word)]);
  }

  // Map(word -> index of the hardest level that marks it): the word's band.
  // Words of no level (added by the learner, forms of easier words) have none.
  function bands(pack, data) {
    const index = new Map();
    pack.levels.forEach((level, i) => (data.levels[level.id] ?? []).forEach(word => index.set(word, i)));
    return index;
  }

  const keys = (words) => new Set(words.filter(row => Array.isArray(row) && typeof row[0] === 'string')
    .map(row => LB.normalizeWord(row[0])));

  // The stored list `words` moved from the level list `from` to `to`, each
  // {dict, list}. known: words the learner took out of earlier level lists.
  // Returns {words, known}: words taken out stay out, also on a later switch
  // back, words added stay in, definitions not edited follow the new dictionary.
  function switchWords(words, known, from, to) {
    const old = new Set(from.list), next = new Set(to.list), have = keys(words);
    const out = new Set([...known, ...from.list].filter(w => !have.has(w)));
    const kept = words.flatMap(row => {
      if(!Array.isArray(row) || typeof row[0] !== 'string') return [row];
      const word = LB.normalizeWord(row[0]), fresh = to.dict.get(word);
      if(old.has(word) && !next.has(word)) return [];
      return [fresh && row[1] === from.dict.get(word) ? [row[0], fresh] : row];
    });
    const added = to.list.filter(w => !have.has(w) && !out.has(w)).map(w => [w, to.dict.get(w)]);
    return {words: [...kept, ...added], known: [...out].sort()};
  }

  // How far the learner is through the band of their level (words the next
  // level knows): {band, known, total, next}, null for an unknown level.
  function progress(pack, levels, levelId, words) {
    const i = pack.levels.findIndex(l => l.id === levelId);
    if(i < 0) return null;
    const next = pack.levels[i + 1], harder = new Set(next ? levels[next.id] : []), have = keys(words);
    const band = (levels[levelId] ?? []).filter(w => !harder.has(w));
    return {band: pack.levels[i].band, known: band.filter(w => !have.has(w)).length, total: band.length, next};
  }

  // Share of the band known when moving up a level is suggested.
  const READY = 0.8;

  return {PACKS, READY, getPack, pickPack, getLevel, loadLevels, loadPack, levelWords, bands, switchWords, progress};
})();

if (typeof module !== 'undefined') module.exports = LexiBridgePacks;
